

meta_title: "Mayaa Honk-Kong - Sponsor a child for education"
meta_description: "The goal of Mayaa Hong Kong is to support children education, by developing individual patronage."
meta_image: "mayaa-banner.gif"                           # Une image dans votre dossier app/assets/images/
